### ISSUE TITLE
various errors

### ISSUE THREAD

**Issue by daimor** [grongierisc/iris-dollar-list#1]
```
>>> DollarList.from_bytes(b'')
$lb("")
```
expected to be just $lb()

```
USER>zw $c(1)
$lb()

USER>zw $c(1,1)
$lb(,)
```

and in python
```
>>> DollarList.from_bytes(b'\x01')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/irisowner/.local/lib/python3.10/site-packages/iris_dollar_list/dollar_list.py", line 547, in from_bytes
    cls.items = DollarListReader(buffer).items
  File "/home/irisowner/.local/lib/python3.10/site-packages/iris_dollar_list/dollar_list.py", line 59, in __init__
    self.read_buffer()
  File "/home/irisowner/.local/lib/python3.10/site-packages/iris_dollar_list/dollar_list.py", line 66, in read_buffer
    item = self.get_next_item()
  File "/home/irisowner/.local/lib/python3.10/site-packages/iris_dollar_list/dollar_list.py", line 208, in get_next_item
    item = self.get_item(self.next_offset)
  File "/home/irisowner/.local/lib/python3.10/site-packages/iris_dollar_list/dollar_list.py", line 195, in get_item
    item.dollar_type = self.get_item_type(
  File "/home/irisowner/.local/lib/python3.10/site-packages/iris_dollar_list/dollar_list.py", line 94, in get_item_type
    typ = self.buffer[offset+meta_offset-1]
IndexError: index out of range
```

**Comment by daimor** [comment]
```
>>> DollarList.from_bytes(b'\x02\x05')
$lb(0)
>>> DollarList.from_bytes(b'\x03\x05\x01')
$lb(1)
```
!=
```
USER>zw $c(2,5)
$lb(-1)

USER>zw $c(3,5,1)
$lb(-255)
```
